In [ ]:
import tensorflow as tf
from tensorflow.keras import datasets,layers,models
import matplotlib.pyplot as plt
import numpy as np
from tensorflow import keras

In [ ]:
cifar10=keras.datasets.cifar10

In [ ]:
(x_train,y_train),(x_test,y_test)=cifar10.load_data()

In [ ]:
x_train.shape

(50000, 32, 32, 3)

In [ ]:
y_train.shape

(50000, 1)

In [ ]:
y_train[:5]

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [ ]:
x_train=x_train/255.0
x_test=x_test/255.0

In [ ]:
x_test

array([[[[0.61960784, 0.43921569, 0.19215686],
         [0.62352941, 0.43529412, 0.18431373],
         [0.64705882, 0.45490196, 0.2       ],
         ...,
         [0.5372549 , 0.37254902, 0.14117647],
         [0.49411765, 0.35686275, 0.14117647],
         [0.45490196, 0.33333333, 0.12941176]],

        [[0.59607843, 0.43921569, 0.2       ],
         [0.59215686, 0.43137255, 0.15686275],
         [0.62352941, 0.44705882, 0.17647059],
         ...,
         [0.53333333, 0.37254902, 0.12156863],
         [0.49019608, 0.35686275, 0.1254902 ],
         [0.46666667, 0.34509804, 0.13333333]],

        [[0.59215686, 0.43137255, 0.18431373],
         [0.59215686, 0.42745098, 0.12941176],
         [0.61960784, 0.43529412, 0.14117647],
         ...,
         [0.54509804, 0.38431373, 0.13333333],
         [0.50980392, 0.37254902, 0.13333333],
         [0.47058824, 0.34901961, 0.12941176]],

        ...,

        [[0.26666667, 0.48627451, 0.69411765],
         [0.16470588, 0.39215686, 0.58039216]

In [ ]:
x_train.shape

(50000, 32, 32, 3)

In [ ]:
#build the simple neural network
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Input

In [ ]:
ann = models.Sequential([
        layers.Flatten(input_shape=(32,32,3)),
        layers.Dense(3000, activation='relu'),
        layers.Dense(1000, activation='relu'),
        layers.Dense(10, activation='sigmoid')    
    ])

ann.compile(optimizer='SGD',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

ann.fit(x_train, y_train, epochs=5)

Epoch 1/5
1563/1563 [==============================] - 11s 6ms/step - loss: 1.9274 - accuracy: 0.3063
Epoch 2/5
1563/1563 [==============================] - 9s 6ms/step - loss: 1.6414 - accuracy: 0.4246
Epoch 3/5
1563/1563 [==============================] - 9s 6ms/step - loss: 1.5533 - accuracy: 0.4508
Epoch 4/5
1563/1563 [==============================] - 9s 6ms/step - loss: 1.4959 - accuracy: 0.4713
Epoch 5/5
1563/1563 [==============================] - 9s 6ms/step - loss: 1.4380 - accuracy: 0.4967


In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
y_pred=ann.predict(x_test)

In [ ]:
y_pred

array([[0.33731985, 0.36480835, 0.714301  , ..., 0.0449012 , 0.66258264,
        0.06984014],
       [0.83846754, 0.95958275, 0.20898938, ..., 0.09660633, 0.9873297 ,
        0.97590065],
       [0.94971734, 0.9017505 , 0.28207213, ..., 0.18312176, 0.9849123 ,
        0.8562288 ],
       ...,
       [0.08777983, 0.04016389, 0.8808988 , ..., 0.50912285, 0.2637029 ,
        0.18317556],
       [0.23185147, 0.0902769 , 0.7834634 , ..., 0.30586946, 0.06934881,
        0.15796919],
       [0.52001905, 0.14685512, 0.74691755, ..., 0.8612835 , 0.160037  ,
        0.2966319 ]], dtype=float32)

In [ ]:
y_pred_classes = [np.argmax(element) for element in y_pred]

In [ ]:
y_pred_classes

[3,
 8,
 8,
 8,
 4,
 6,
 3,
 4,
 4,
 1,
 8,
 9,
 5,
 7,
 9,
 8,
 3,
 4,
 8,
 6,
 4,
 2,
 0,
 9,
 4,
 2,
 4,
 4,
 9,
 4,
 6,
 4,
 4,
 5,
 9,
 1,
 4,
 9,
 9,
 5,
 0,
 6,
 9,
 4,
 0,
 9,
 3,
 8,
 4,
 4,
 9,
 8,
 6,
 3,
 8,
 8,
 5,
 9,
 4,
 4,
 4,
 3,
 6,
 9,
 2,
 2,
 1,
 0,
 3,
 9,
 4,
 4,
 8,
 8,
 0,
 4,
 9,
 3,
 3,
 8,
 8,
 1,
 2,
 2,
 2,
 7,
 8,
 8,
 8,
 8,
 8,
 4,
 8,
 2,
 4,
 3,
 4,
 0,
 2,
 7,
 4,
 4,
 6,
 3,
 1,
 1,
 3,
 6,
 3,
 5,
 4,
 2,
 2,
 4,
 9,
 4,
 0,
 9,
 2,
 4,
 8,
 4,
 1,
 2,
 0,
 2,
 8,
 3,
 4,
 4,
 4,
 1,
 8,
 9,
 1,
 2,
 9,
 7,
 4,
 8,
 4,
 1,
 3,
 5,
 8,
 2,
 3,
 5,
 5,
 3,
 8,
 9,
 8,
 8,
 4,
 5,
 2,
 8,
 3,
 4,
 2,
 7,
 3,
 4,
 9,
 7,
 8,
 4,
 7,
 0,
 9,
 7,
 0,
 8,
 4,
 9,
 8,
 5,
 3,
 0,
 9,
 7,
 4,
 2,
 4,
 8,
 6,
 2,
 7,
 0,
 4,
 3,
 5,
 3,
 7,
 4,
 8,
 4,
 3,
 3,
 5,
 8,
 8,
 2,
 1,
 5,
 8,
 4,
 4,
 8,
 2,
 1,
 3,
 7,
 4,
 2,
 8,
 9,
 0,
 4,
 4,
 3,
 9,
 3,
 9,
 9,
 3,
 2,
 3,
 2,
 3,
 9,
 3,
 4,
 8,
 0,
 4,
 0,
 3,
 5,
 1,
 8,
 7,
 8,
 0,
 3,
 4,
 0,
 5,
 1,


In [ ]:
classification_report(y_test,y_pred_classes)

'              precision    recall  f1-score   support\n\n           0       0.55      0.52      0.53      1000\n           1       0.72      0.48      0.58      1000\n           2       0.37      0.27      0.32      1000\n           3       0.32      0.42      0.36      1000\n           4       0.28      0.66      0.40      1000\n           5       0.43      0.28      0.34      1000\n           6       0.67      0.27      0.38      1000\n           7       0.66      0.39      0.49      1000\n           8       0.52      0.71      0.60      1000\n           9       0.57      0.56      0.56      1000\n\n    accuracy                           0.46     10000\n   macro avg       0.51      0.46      0.46     10000\nweighted avg       0.51      0.46      0.46     10000\n'

#Now lets build CNN network

In [ ]:
cnn=models.Sequential([
                       layers.Conv2D(filters=32,kernel_size=(3,3),activation="relu",input_shape=(32,32,3)),
                       layers.MaxPooling2D((2,2)),
                       layers.Conv2D(filters=64,kernel_size=(3,3),activation="relu"),
                       layers.MaxPooling2D((2,2)),
                       layers.Conv2D(filters=128,kernel_size=(3,3),activation="relu"),
                       layers.MaxPooling2D((2,2)),
                       layers.Flatten(),
                       layers.Dense(64,activation="relu"),
                       layers.Dense(10,activation="softmax")
])

In [ ]:
cnn.compile(optimizer="adam",
            loss="sparse_categorical_crossentropy",
            metrics=["accuracy"])

In [ ]:
cnn.fit(x_train,y_train,epochs=10)

Epoch 1/10
1563/1563 [==============================] - 37s 7ms/step - loss: 1.7825 - accuracy: 0.3330
Epoch 2/10
1563/1563 [==============================] - 10s 6ms/step - loss: 1.1773 - accuracy: 0.5843
Epoch 3/10
1563/1563 [==============================] - 10s 6ms/step - loss: 0.9981 - accuracy: 0.6520
Epoch 4/10
1563/1563 [==============================] - 10s 6ms/step - loss: 0.8914 - accuracy: 0.6889
Epoch 5/10
1563/1563 [==============================] - 10s 6ms/step - loss: 0.8102 - accuracy: 0.7157
Epoch 6/10
1563/1563 [==============================] - 10s 6ms/step - loss: 0.7397 - accuracy: 0.7430
Epoch 7/10
1563/1563 [==============================] - 10s 6ms/step - loss: 0.6796 - accuracy: 0.7622
Epoch 8/10
1563/1563 [==============================] - 10s 6ms/step - loss: 0.6386 - accuracy: 0.7800
Epoch 9/10
1563/1563 [==============================] - 10s 6ms/step - loss: 0.5884 - accuracy: 0.7961
Epoch 10/10
1563/1563 [==============================] - 10s 6ms/step - l

In [ ]:
#Predict for the test dataset
y_pred=cnn.predict(x_test)

In [ ]:
y_pred

array([[2.03339593e-03, 1.65675337e-05, 1.23429298e-03, ...,
        2.86585971e-04, 9.38788289e-05, 1.91748759e-03],
       [1.24091364e-01, 2.01390624e-01, 6.33559655e-04, ...,
        1.12520229e-05, 6.49575114e-01, 2.40045190e-02],
       [6.21860087e-01, 3.14467065e-02, 1.90910399e-02, ...,
        5.02566472e-02, 1.15735225e-01, 2.37898380e-02],
       ...,
       [8.52300491e-06, 2.77466569e-07, 1.32775609e-03, ...,
        6.55440381e-03, 3.91998947e-06, 1.48088134e-06],
       [1.09766103e-01, 3.49284172e-01, 7.57685229e-02, ...,
        2.04469106e-04, 7.25580321e-04, 2.87620351e-02],
       [2.11292726e-08, 1.65260994e-09, 3.40636070e-05, ...,
        9.95257318e-01, 3.38865980e-09, 2.96153448e-08]], dtype=float32)

In [ ]:
y_classes=[np.argmax(elemen) for elemen in y_pred]

In [ ]:
cm=confusion_matrix(y_test,y_classes)

In [ ]:
cm

array([[747,  11,  70,  24,  21,  15,  12,  12,  37,  51],
       [ 17, 759,   9,  16,   3,   9,  11,   4,  12, 160],
       [ 58,   2, 598, 100,  68,  96,  46,  15,   5,  12],
       [ 12,   3,  51, 587,  32, 225,  42,  25,   6,  17],
       [ 13,   3,  90, 109, 599,  77,  53,  48,   6,   2],
       [  4,   2,  48, 172,  25, 697,  16,  27,   1,   8],
       [  4,   6,  31,  97,  21,  37, 785,   7,   4,   8],
       [ 17,   1,  30,  67,  54, 114,  11, 683,   0,  23],
       [115,  25,  15,  48,   7,  13,   7,   5, 716,  49],
       [ 18,  38,  13,  21,   2,  14,  13,   6,  13, 862]])